-- MySQL Script generated by MySQL Workbench
-- 03/23/16 05:33:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tourism
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tourism
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tourism` DEFAULT CHARACTER SET latin1 ;
USE `tourism` ;

-- -----------------------------------------------------
-- Table `tourism`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`address` (
  `address_id` INT(11) NOT NULL AUTO_INCREMENT,
  `place_id` INT(11) NULL DEFAULT NULL,
  `district_id` INT(11) NULL DEFAULT NULL,
  `division_id` INT(11) NULL DEFAULT NULL,
  `city_id` INT(11) NULL DEFAULT NULL,
  `thana_id` INT(11) NULL DEFAULT NULL,
  `address_description` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tourism`.`guides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`guides` (
  `guidesID` INT(11) NOT NULL AUTO_INCREMENT,
  `guidesName` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`guidesID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tourism`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`organization` (
  `organizationID` INT(11) NOT NULL AUTO_INCREMENT,
  `organizationName` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`organizationID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tourism`.`placetag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`placetag` (
  `place_id` INT(11) NULL DEFAULT NULL,
  `tag_id` INT(11) NULL DEFAULT NULL,
  `placeTag_id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`placeTag_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tourism`.`travellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`travellers` (
  `traveller_id` INT(11) NOT NULL AUTO_INCREMENT,
  `traveller_name` VARCHAR(256) NOT NULL,
  `traveller_birthday` DATE NOT NULL,
  `traveller_email` VARCHAR(128) NOT NULL,
  `traveller_password` VARCHAR(256) NOT NULL,
  `traveller_active` SMALLINT NOT NULL,
  `travellerCountry_id` INT NOT NULL,
  PRIMARY KEY (`traveller_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tourism`.`district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`district` (
  `district_id` INT NOT NULL,
  `district_name` VARCHAR(45) NULL,
  PRIMARY KEY (`district_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tourism`.`division`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`division` (
  `division_id` INT NOT NULL,
  `division_name` VARCHAR(45) NULL,
  PRIMARY KEY (`division_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tourism`.`thana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`thana` (
  `thana_id` INT NOT NULL,
  `thana_name` VARCHAR(45) NULL,
  PRIMARY KEY (`thana_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tourism`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`city` (
  `city_id` INT NOT NULL,
  `city_name` VARCHAR(45) NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tourism`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`country` (
  `country_id` INT NOT NULL,
  `country_name` VARCHAR(45) NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tourism`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`tags` (
  `tag_id` INT NOT NULL,
  `tag_name` VARCHAR(45) NULL,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tourism`.`places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`places` (
  `place_id` INT NOT NULL,
  `place_description` VARCHAR(2048) NULL,
  `place_address` INT NULL,
  PRIMARY KEY (`place_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
